### ISSUE TITLE
arduino.h: No such file or directory

### ISSUE THREAD

**Issue by g1ra** [blackhack/LCD_I2C#1]
In file included from /tmp/arduino_modified_sketch_560284/Custom_Chars.ino:20:0:
/home/bob2/Arduino/libraries/LCD_I2C/src/LCD_I2C.h:23:10: fatal error: arduino.h: No such file or directory
 #include "arduino.h"
          ^~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Mega or Mega 2560.

**Comment by g1ra** [comment]
Fix is changing line to : 
#include "Arduino.h"

**Comment by blackhack** [comment]
Fix applied in https://github.com/blackhack/LCD_I2C/commit/b72bf9e051e55252739255ba3a0c93d222113045

Thank you.
