### ISSUE TITLE
Printing only the first character .

### ISSUE THREAD

**Issue by g1ra** [blackhack/LCD_I2C#2]
Running the examples . The first character is displayed only : 

```
    lcd.setCursor(1, 5); // Or setting the cursor in the desired position.
    lcd.print("World!");
```
This display only the letter "W" .

**Comment by blackhack** [comment]
Fixed in https://github.com/blackhack/LCD_I2C/commit/9b5d48430139a28aafbb5f6dac015f520b3b49fb

An update should be available through Arduino's Library Manager in the next few hours.

Thank you for reporting.
